spring.view.prefix: /WEB-INF/jsp/
spring.view.suffix: .jsp

spring.datasource.url=jdbc:postgresql://localhost/trainingsdb
spring.datasource.username=training
spring.datasource.password=training
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true


# server.tomcat.additional-tld-skip-patterns=*.jar

spring.main.allow-bean-definition-overriding=true

server.port=8080
# server.port=8443
# server.ssl.key-store-type=PKCS12
# server.ssl.key-store=classpath:vulnerads.de.p12
# server.ssl.key-store-password=sosec
