spring.datasource.url=jdbc:postgresql://localhost/trainingsdb
spring.datasource.username=training
spring.datasource.password=training
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
# prevents hibernate from ordering the columns, so that, e.g., ID remains col1
spring.jpa.properties.hibernate.column_ordering_strategy=legacy

spring.main.allow-bean-definition-overriding=true
spring.web.error.include-message=always


server.port=8080
# server.port=8443
# server.ssl.key-store-type=PKCS12
# server.ssl.key-store=classpath:vulnerads.de.p12
# server.ssl.key-store-password=sosec
